# Make a copy of this file called database.yml with the real database credentials below
:development: &defaults
  :adapter: mysql
  :database: darlow_development
  :username: darlow
  :password: 
  :host: localhost

:test:
  <<: *defaults
  :database: darlow_test

:production:
  <<: *defaults
  :database: darlow_production